import { Executor } from "@dreamx-development/hodlbonds-blockchain-executor-dto"
import ejs from "ejs"
import fs from "node:fs"

const warning =
  "" +
  "#\n" +
  "# DO NOT EDIT THIS FILE #\n" +
  "#\n" +
  "# Edit the template file in the root folder instead.\n" +
  "# Then run `pnpm prepare-cloudbuild-template`\n" +
  "#\n\n"

const executors = Object.values(Executor).filter((executor) => executor !== "UnitTest")

const yaml = ejs.render(fs.readFileSync("cloudbuild-template.ejs", "utf8"), { executors })

fs.writeFileSync("cloudbuild.yaml", warning + yaml)
