import { parseAbi } from "viem"

export const bondMarketplaceAbi = parseAbi([
  "function approvedTokenSetIds(uint256) view returns (uint256)",
  "function approvedTokenSets(uint256) view returns (address erc1155Address, address tradeToken)",
  "function cancelListing(uint256 _listingId)",
  "function createListing(uint256 _tokenSetId, uint256 _collectionId, uint256 _price, address _buyer)",
  "function feeRecipientAddress() view returns (address)",
  "function getListing(uint256 _listingId) view returns ((uint256 tokenSetId, uint256 collectionId, address seller, uint256 price, uint64 startedAt, address buyer))",
  "function getListing(uint256 _tokenSetId, uint256 _collectionId) view returns ((uint256 tokenSetId, uint256 collectionId, address seller, uint256 price, uint64 startedAt, address buyer))",
  "function getListings(uint256[] _listingIds) view returns ((uint256 tokenSetId, uint256 collectionId, address seller, uint256 price, uint64 startedAt, address buyer)[])",
  "function getListings(uint256[] _tokenSetId, uint256[] _collectionIds) view returns ((uint256 tokenSetId, uint256 collectionId, address seller, uint256 price, uint64 startedAt, address buyer)[])",
  "function getUserListingIds(address _address) view returns (uint256[])",
  "function getUserListings(address _address) view returns ((uint256 tokenSetId, uint256 collectionId, address seller, uint256 price, uint64 startedAt, address buyer)[])",
  "function listings(uint256) view returns (uint256 tokenSetId, uint256 collectionId, address seller, uint256 price, uint64 startedAt, address buyer)",
  "function onERC1155BatchReceived(address, address, uint256[], uint256[], bytes) pure returns (bytes4)",
  "function onERC1155Received(address, address, uint256, uint256, bytes) pure returns (bytes4)",
  "function ownerCut() view returns (uint256)",
  "function purchase(uint256 _listingId)",
  "function setApprovedTokenSet(uint256 _tokenSetId, (address erc1155Address, address tradeToken) _approvedTokenSet)",
  "function setApprovedTokenSetIds(uint256[] _tokenSetIds)",
  "function setApprovedTokenSets(uint256[] _tokenSetIds, (address erc1155Address, address tradeToken)[] _approvedTokenSets)",
  "function totalListings() view returns (uint256)",
  "function userListings(address, uint256) view returns (uint256)",
  "event ApprovedTokenSetSet(uint256 tokenSetId, address erc1155Address, address tradeTokenAddress)",
  "event ListingCancelled(uint256 listingId, uint256 tokenSetId, uint256 collectionId)",
  "event ListingCreated(uint256 listingId, address indexed owner, uint256 indexed tokenSetId, uint256 indexed collectionId, uint256 price, address buyer)",
  "event ListingPurchased(uint256 indexed listingId, uint256 indexed tokenSetId, uint256 collectionId, uint256 totalPrice, address indexed buyer)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error AlreadyOnSale(uint256 collectionId)",
  "error ArrayLengthMismatch(uint256 arrayLength1, uint256 arrayLength2)",
  "error IncorrectNativeTokenAmountSent(uint256 expectedAmount, uint256 actualAmount)",
  "error IncorrectPrivateSaleBuyer(address buyer, address caller)",
  "error InvalidPrice()",
  "error InvalidTokenSetId()",
  "error NativeTokenNotAccepted()",
  "error NotOnSale(uint256 collectionId)",
  "error NotOwner(address caller)",
  "error NotSeller(address caller)",
  "error PaymentTransferFailed()",
  "error ZeroId()",
  "error ZeroSetsProvided()",
])
