import { parseAbi } from "viem"

export const dualTokenVaultAbi = parseAbi([
  "function blackholeSwapExactInputSingle(uint128 _amountIn, uint128 _minAmountOut, address _tokenIn, uint256 _deadline, bytes32[] _proof)",
  "function getBlackholeSwapData() view returns ((address routerV2Address, address pairAddress, bool concentrated))",
  "function getLBSwapData() view returns ((address routerAddress, address tokenPairAddress, uint8 version))",
  "function getVaultConfig() view returns ((uint64 vaultId, address vaultTokenAddress, address stableTokenAddress, address receiptTokenAddress, address chainlinkPriceOracleAddress, uint256 minUSDPricePerBond, address feeSplitterAddress, uint16 managementFee, uint16 performanceFee, uint256 bondPrice, uint16 reserveRatio, uint32 tradingPeriodDuration, uint8 primaryDex))",
  "function getVaultData() view returns ((uint8 vaultState, uint256 startingStableTokenBalance, uint256 startingVaultTokenBalance, address issuerAddress, uint256 creationTimestamp))",
  "function getVaultTokenBalance() view returns ((uint256 vaultTokenBalance, uint256 vaultTokenDecimals, uint256 stableTokenBalance, uint256 stableTokenDecimals))",
  "function issueBond(address _issuerAddress) returns (uint256, uint256, uint256)",
  "function lbSwapExactInputSingle(uint128 _amountIn, uint128 _minAmountOut, address _tokenIn, uint256 _deadline, bytes32[] _proof)",
  "function redeemBond()",
  "event BondIssued(address indexed creator, address indexed vaultToken, address indexed stableToken, uint256 vaultTokenAmount, uint256 stableTokenAmount, uint256 managementFeeAmount)",
  "event BondRedeemed(address indexed redeemer, address indexed vaultToken, address indexed stableToken, uint256 vaultTokenAmount, uint256 stableTokenAmount, uint256 performanceFeeAmount)",
  "event FeeCollected(address indexed to, address indexed token, uint256 amount)",
  "event TradeCompleted(address indexed vaultAddress, address indexed routerAddress, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut, uint256 tokenInBalanceAfterSwap, uint256 tokenOutBalanceAfterSwap)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error BondIssuanceClosed()",
  "error BondNotYetRedeemable()",
  "error FeeTransferFailed()",
  "error IncorrectNativeTokenAmountSent(uint256 expectedAmount, uint256 actualAmount)",
  "error InsufficientOutputAmount(uint256 expected, uint256 actual)",
  "error InvalidInitialization()",
  "error InvalidMerkleProof()",
  "error InvalidPairAddress()",
  "error InvalidPriceData()",
  "error InvalidRouterAddress()",
  "error InvalidTokenAddress()",
  "error InvalidVaultState(uint8 expectedState, uint8 actualState)",
  "error NoValueSentWithTransaction()",
  "error NotInitializing()",
  "error PaymentTransferFailed()",
  "error PoolNotFound()",
  "error PurchaseExceedsBondLimit()",
  "error RedemptionTransferFailed()",
  "error StableTokenTransferFailed()",
  "error StableTokensNotClaimable()",
  "error TradingPeriodClosed()",
  "error ZeroAmountBondRedemption()",
])
