import { parseAbi } from "viem"

export const dualTokenVaultFactoryAbi = parseAbi([
  "function approvedPairIds(uint256) view returns (uint256)",
  "function approvedPairs(uint256) view returns (address stableTokenAddress, address vaultTokenAddress, address wrappedNativeTokenAddress, address routerAddress, address tokenPairAddress, uint8 version, address routerV2Address, address pairAddress, bool concentrated, address chainlinkPriceOracleAddress)",
  "function createVaultAndIssueBond((uint256 bondPrice, uint256 maxStableTokenAmount, uint16 reserveRatio, uint32 tradingPeriodDuration, uint16 pairId, uint8 primaryDex) _userConfigurableParams) payable returns (address)",
  "function feeSplitterAddress() view returns (address)",
  "function getActiveVaultAddresses() view returns (address[])",
  "function getActiveVaultIds() view returns (uint256[])",
  "function getActiveVaults() view returns ((uint64 vaultId, (address vaultAddress, (uint256 bondPrice, uint256 maxStableTokenAmount, uint16 reserveRatio, uint32 tradingPeriodDuration, uint16 pairId, uint8 primaryDex) userConfig) vaultCreationData)[])",
  "function getApprovedPair(uint256 _pairId) view returns ((uint16 pairId, (address stableTokenAddress, address vaultTokenAddress, address wrappedNativeTokenAddress, address routerAddress, address tokenPairAddress, uint8 version, address routerV2Address, address pairAddress, bool concentrated, address chainlinkPriceOracleAddress) approvedPair))",
  "function getApprovedPairs() view returns ((uint16 pairId, (address stableTokenAddress, address vaultTokenAddress, address wrappedNativeTokenAddress, address routerAddress, address tokenPairAddress, uint8 version, address routerV2Address, address pairAddress, bool concentrated, address chainlinkPriceOracleAddress) approvedPair)[])",
  "function getTraderMerkleRoot() view returns (bytes32)",
  "function getVault(uint256 vaultId) view returns ((uint64 vaultId, (address vaultAddress, (uint256 bondPrice, uint256 maxStableTokenAmount, uint16 reserveRatio, uint32 tradingPeriodDuration, uint16 pairId, uint8 primaryDex) userConfig) vaultCreationData))",
  "function getVaults() view returns ((uint64 vaultId, (address vaultAddress, (uint256 bondPrice, uint256 maxStableTokenAmount, uint16 reserveRatio, uint32 tradingPeriodDuration, uint16 pairId, uint8 primaryDex) userConfig) vaultCreationData)[])",
  "function managementFee() view returns (uint16)",
  "function minUSDPricePerBond() view returns (uint256)",
  "function nextVaultId() view returns (uint64)",
  "function performanceFee() view returns (uint16)",
  "function receiptTokenAddress() view returns (address)",
  "function setApprovedPair(uint256 _pairId, (address stableTokenAddress, address vaultTokenAddress, address wrappedNativeTokenAddress, address routerAddress, address tokenPairAddress, uint8 version, address routerV2Address, address pairAddress, bool concentrated, address chainlinkPriceOracleAddress) _approvedPair)",
  "function setApprovedPairIds(uint256[] _pairIds)",
  "function setApprovedPairs(uint256[] _pairIds, (address stableTokenAddress, address vaultTokenAddress, address wrappedNativeTokenAddress, address routerAddress, address tokenPairAddress, uint8 version, address routerV2Address, address pairAddress, bool concentrated, address chainlinkPriceOracleAddress)[] _approvedPairs)",
  "function setFeeSplitterAddress(address _feeSplitterAddress)",
  "function setManagementFee(uint16 _managementFee)",
  "function setMinUSDPricePerBond(uint256 _minUSDPricePerBond)",
  "function setPerformanceFee(uint16 _performanceFee)",
  "function setTraderMerkleRoot(bytes32 _traderMerkleRoot)",
  "function vaultImplementationAddress() view returns (address)",
  "function vaults(uint256) view returns (address vaultAddress, (uint256 bondPrice, uint256 maxStableTokenAmount, uint16 reserveRatio, uint32 tradingPeriodDuration, uint16 pairId, uint8 primaryDex) userConfig)",
  "event ApprovedPairSet(address indexed sender, uint256 indexed pairId, (address stableTokenAddress, address vaultTokenAddress, address wrappedNativeTokenAddress, address routerAddress, address tokenPairAddress, uint8 version, address routerV2Address, address pairAddress, bool concentrated, address chainlinkPriceOracleAddress) approvedPair)",
  "event VaultCreated(address indexed creator, uint256 indexed vaultId, uint256 indexed pairId, address vaultAddress, (address stableTokenAddress, address vaultTokenAddress, address wrappedNativeTokenAddress, address routerAddress, address tokenPairAddress, uint8 version, address routerV2Address, address pairAddress, bool concentrated, address chainlinkPriceOracleAddress) approvedPair, (uint64 vaultId, address vaultTokenAddress, address stableTokenAddress, address receiptTokenAddress, address chainlinkPriceOracleAddress, uint256 minUSDPricePerBond, address feeSplitterAddress, uint16 managementFee, uint16 performanceFee, uint256 bondPrice, uint16 reserveRatio, uint32 tradingPeriodDuration, uint8 primaryDex) vaultParameters)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error ArrayLengthMismatch(uint256 arrayLength1, uint256 arrayLength2)",
  "error FailedDeployment()",
  "error IncorrectNativeTokenAmountSent(uint256 expectedAmount, uint256 actualAmount)",
  "error InsufficientBalance(uint256 balance, uint256 needed)",
  "error InvalidPairId(uint16 pairId)",
  "error NoValueSentWithTransaction()",
  "error PaymentTransferFailed()",
  "error ReserveRatioOutOfBounds(uint16 reserveRatio)",
  "error StableTokenAmountBelowMinimumRequired(uint256 minStableTokenAmount, uint256 actualStableTokenAmount)",
  "error StableTokenAmountExceedsMaximumAllowed(uint256 maxStableTokenAmount, uint256 actualStableTokenAmount)",
  "error TradingPeriodDurationOutOfBounds(uint32 tradingPeriodDuration)",
  "error VaultDeployerAlreadyDeployed()",
  "error ZeroPairsProvided()",
])
