import { parseAbi } from "viem"

export const vaultAbi = parseAbi([
  "function blackholeSwapExactInputSingle(uint128 _amountIn, uint128 _minAmountOut, address _tokenIn, uint256 _deadline)",
  "function claimStableTokens()",
  "function depositStableTokens()",
  "function getBlackholeSwapData() view returns ((address routerV2Address, address pairAddress, bool concentrated))",
  "function getLBSwapData() view returns ((address routerAddress, address tokenPairAddress, uint8 version))",
  "function getVaultConfig() view returns ((uint256 bondPrice, address feeSplitterAddress, uint64 vaultId, uint32 reserveRatio, address vaultTokenAddress, uint64 bondSaleStart, uint32 fundingPeriodDuration, address stableTokenAddress, uint64 bondSaleEnd, uint32 tradingPeriodDuration, address receiptTokenAddress, uint64 bondLimit, uint32 hurdleRate, address affiliateAddress, uint8 tradingStrategy, uint16 managementFee, uint16 performanceFee, address chainlinkPriceOracleAddress))",
  "function getVaultState() view returns (uint8, uint256, uint256, uint256, uint256, uint256)",
  "function lbSwapExactInputSingle(uint128 _amountIn, uint128 _minAmountOut, address _tokenIn, uint256 _deadline)",
  "function purchaseBond(uint256 _numberOfBonds) payable",
  "function redeemBond(uint256 _numberOfBonds)",
  "event BondPurchased(address indexed buyer, uint256 amount)",
  "event BondRedeemed(address indexed redeemer, uint256 amount)",
  "event StableTokensDeposited(address indexed provider, uint256 amount)",
  "event StableTokensWithdrawn(address indexed provider, uint256 amount)",
  "event TradeCompleted(address indexed vaultAddress, address indexed routerAddress, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountOut)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error BondNotYetRedeemable()",
  "error BondSaleClosed()",
  "error IncorrectNativeTokenAmountSent()",
  "error InvalidInitialization()",
  "error InvalidPairAddress()",
  "error InvalidPriceData()",
  "error InvalidRouterAddress()",
  "error InvalidTokenAddress()",
  "error InvalidVaultState()",
  "error NotInitializing()",
  "error PaymentTransferFailed()",
  "error PoolNotFound()",
  "error PurchaseExceedsBondLimit()",
  "error RedemptionTransferFailed()",
  "error StableTokenTransferFailed()",
  "error StableTokensNotClaimable()",
  "error TradingPeriodClosed()",
  "error ZeroAmountBondRedemption()",
])
